# Generated by Django 4.0.3 on 2022-12-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPersonVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='service_rest.automobilevo')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='service_rest.salespersonvo')),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='owner',
            field=models.CharField(default='Ally', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomerVO',
        ),
    ]
