# Generated by Django 4.0.3 on 2022-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_salespersonvo_salevo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salevo',
            name='automobile',
        ),
        migrations.RemoveField(
            model_name='salevo',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='appointment_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SalesPersonVO',
        ),
        migrations.DeleteModel(
            name='SaleVO',
        ),
    ]
