# Generated by Django 4.0.3 on 2022-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_serviceappointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='appointment_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
