# Generated by Django 4.0.3 on 2022-12-12 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_remove_serviceappointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appointment_datetime',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
